image: 
  file: .gitpod.Dockerfile
tasks:
  - name: LaTeX auto-rebuild
    command: >
      while find . -name '*.tex' | xargs inotifywait -qqre modify .; do \
        echo X | pdflatex notes.tex || echo "Error"; \
      done
  - init: pip3 install -r requirements.txt
vscode:
  extensions:
    - efoerster.texlab@1.10.0:/Vq+k9Ug/81LYWajjTgMpA==
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
    addLabel: gitpod-ready
